export const DRUGS_TABLE=[
{"id":0,"name_pol":"Paracetamol","name_lat":"Paracetamolum","dosage":30,"img_link":"https://www.i-apteka.pl/data/include/img/news/1425908509.jpg","description":"Lek z grupy niesteroidowych leków przeciwzapalnych (NLPZ) głównie używany przeciwbólowo. Osiąga maksymalne stężenie we krwi w 30-60 minut. Czas działania wynosi około 4 godziny.","application":"Przeciwbólowe,Stany gorączkowe","sub_group":"NLPZ","lethal_dose":338},
{"id":1,"name_pol":"Ibuprofen","name_lat":"Ibuprofenum","dosage":40,"img_link":"https://www.researchgate.net/profile/Murad_Abualhasan/publication/270283844/figure/fig1/AS:613968762642434@1523392968418/Chemical-structure-of-Ibuprofen.png","description":"Lek z grupy niesteroidowych leków przeciwzapalnych (NLPZ) używany przeciwbólowo, przeciwzapalnie oraz przeciwgorączkowo. Maksymalne stężenie we krwi osiąga po około 1-2h. Efekt przeciwbólowy utrzymuję się przez 6h a przeciwgorączkowy ok. 8h.","application":"Przeciwbólowe,Stany gorączkowe,Przeciwzapalne","sub_group":"NLPZ","lethal_dose":636},
{"id":2,"name_pol":"Pseudoefedryna","name_lat":"Pseudoephedrini","dosage":1.7,"img_link":"https://upload.wikimedia.org/wikipedia/commons/6/6b/Pseudoephedrine_S%2CS_ephedrine_comparison.png","description":"Lek z grupy amin sympatykomimetycznych, użyany w \r\ncelach łagodzenia objawów grypy, niedrożności zatok, \r\nkataru, bólu głowy oraz gorączki. Działanie rozpoczyna się po \r\nokoło 30 minutach od przyjęcia pierwszej dawki i utrzymuję się przez 4h.","application":"Grypa,Niedrożność zatok,Gorączka,Katar","sub_group":"Fenyloetyloaminy, Sympatykomimetyki","lethal_dose":660},
{"id":3,"name_pol":"Ketoprofen","name_lat":"Ketoprofenum","dosage":0,"img_link":"https://www.researchgate.net/publication/321206110/figure/fig2/AS:563333200072704@1511320509273/Chemical-structure-of-ketoprofen.png","description":"Lek z grupy niesteroidowych leków przeciwbólowych (NLPZ) \r\nwykazuje silne działanie przeciwzapalne, przeciwgorączkowe\r\noraz przeciwbólowe. Pierwsze efekty pojawiają się po 30 minutach \r\nod przyjęcia pierwszej dawki leku, maksymalne stężenie osiąga po 80 minutach.","application":"Przeciwbólowe,Przeciwzapalne,Przeciwgorączkowe","sub_group":"NLPZ","lethal_dose":360},
{"id":4,"name_pol":"Cetyryzyna","name_lat":"Cetirizinum","dosage":0,"img_link":"https://upload.wikimedia.org/wikipedia/commons/thumb/c/c5/Cetirizine_structure.svg/1200px-Cetirizine_structure.svg.png","description":"Lek przeciwhistaminowy drugiej generacji, antagonista receptorów H1. \r\nStosowany przy alergicznym zapaleniu spojówek, pokrzywce i katarze siennym.\r\nCzas połowicznego rozpadu wacha się między 6.5h - 10h.","application":"Katar sienny,Zapalenie Spojówek,Alergia,Pokrzywka","sub_group":"Antyhistamina","lethal_dose":365},
{"id":5,"name_pol":"Loratadyna","name_lat":"Loratadine","dosage":0.175,"img_link":"https://pubchem.ncbi.nlm.nih.gov/image/imgsrv.fcgi?cid=3957&t=l","description":"Lek przeciwhistaminowy drugiej generacji, antagonista obwodowych receptorów H1.\r\nStosowana przy alergicznym zapaleniu błony śluzowej nosa, pokrzywce i katarze siennym.\r\nMaksymalne stężenie we krwi występuje po 1h - 1.5h. Średni czas rozpadu połowicznego\r\nwynosi ok 8.5h, ale czas działania aktywnych metabolitów może  osiągać nawet 28h.","application":"Alergia,Zapalenie błony śluzowej,Pokrzywka,Katar sienny","sub_group":"Antyhistamina","lethal_dose":0},
{"id":6,"name_pol":"Tramadol","name_lat":"Tramadoli","dosage":1,"img_link":"https://pubchem.ncbi.nlm.nih.gov/image/imgsrv.fcgi?cid=33741&t=l","description":"Silnie działający lek przeciwbólowy z grupy opioidów.\r\nOprócz działania przeciwbólowego wykazuje również silne działanie przeciwkaszlowe.\r\nPrzy podaniu doustnym działa ok. 5 razy słabiej od morfiny.\r\nDziałanie przeciwbólowe rozpoczyna się po 15-30min i trwa 3-4h.","application":"Przeciwbólowe,Premedykacja,Przeciwkaszlowe","sub_group":"Opioid","lethal_dose":145},
{"id":7,"name_pol":"Morfina","name_lat":"Morphinum","dosage":0,"img_link":"https://upload.wikimedia.org/wikipedia/commons/thumb/3/33/Morphin_-_Morphine.svg/220px-Morphin_-_Morphine.svg.png","description":"Bardzo silny lek narkotyczny, z grupy opiatów.\r\nStosowany przeciwbólowo w silnych bólach np. nowotworowych.\r\nŚredni czas rozpadu połowicznego wynosi ok 3h, ale zostały opracowane tabletki\r\no spowolnionym uwalnianiu przy których efekt przeciwbólowy może utrzymywać się nawet 12h.","application":"Przeciwbólowo,Przeciwkaszlowo","sub_group":"Opiat,Opioid","lethal_dose":0}
];
export const DRUGS_CORELATIONS=[
{"id_interaction":0,"id_primary":3,"id_secondary":1,"danger_scale":2,"side_effects":"Wrzody"},
{"id_interaction":1,"id_primary":7,"id_secondary":6,"danger_scale":3,"side_effects":"Depresja układu oddechowego"}
];